language: python
python:
  - "2.7"
install: "pip install ontodocs -U"
script: "python newSpecGenerator.py && cp 404.html ${TRAVIS_BUILD_DIR}/spec && touch ${TRAVIS_BUILD_DIR}/spec/.nojekyll"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  fqdn: ethon.consensys.net
  local_dir: "${TRAVIS_BUILD_DIR}/spec"
  on:
    branch: master
